### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by CashHash123** [rubenmv/chrome-extension-custom-button#1]
I need to use the open url feature, but i need to have it open with out the https:// or http://   ,

Like i need   to use for example,  Hello://us.bape.com/collections/all/products/1e73-109-909    - when the page i am on is https://us.bape.com/collections/all/products/1e73-109-909

Is it possible to do this?

Thanks so much for your help

**Comment by rubenmv** [comment]
Hi! sorry for the late response. No there's no way to do it right now, what you are asking for is a little bit too specific to implement it and I want it to keep it really simple.

**Comment by CashHash123** [comment]
Thanks for the answers, 

One more question,

Is is possible to only use the actual site URLlike  https://www.google.com and not https://www.google.com/search?q=remove  if you are on the later page?

thanks

**Comment by rubenmv** [comment]
Sure, that seems reasonable, but I think I'll add an "advanced settings" section or something like that. I take note.

**Comment by CashHash123** [comment]
Sounds great

**Comment by rubenmv** [comment]
Hi, I just uploaded a new version with that feature, it's on the advanced options section. If you find any problem with it please let me know.

**Comment by CashHash123** [comment]
Thanks!!

So far so good!!!!
